com/urls.py
from django.urls import path
from .import views


app_name = 'customer'

urlpatterns =[
   
    path('customerdashboard', views.dashboard, name ='dashboard'),
    path('addtocart/<int:product_id>/', views.add_cart, name = "addtocart"),
    path('cartlist', views.check_list, name = 'checkList'),
    path('deletecart/<int:cart_id>', views.deleteCart, name = 'deleteCart'),
    path('deliveryinfo', views.delivery, name ='delivery'),
    path('yourorder/<int:id>', views.yourorder, name = 'yourorder'),
]

owner/urls.py
from django.urls import path
from .import views

app_name = 'owner'
 
urlpatterns = [
   path('admindashboard', views.ownerDashboard, name ='ownerDashboard'),
   path('add_category', views.add_category, name = 'add_category'),
   path('addsubcategory', views.addsubcat, name = 'add_sub_cat'),
   path('add_product', views.product_add, name = 'add_product'),
   path('adminOrder', views.adminOrder, name = 'adminOrder'),
   path('sent_order/<int:id>',views.sent_order, name = 'sent_order'),
   path('userlist', views.userlist, name = 'user_list'),
]

sale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('customer/', include('com.urls', namespace = 'customer')),
    path('adminpage/', include('owner.urls', namespace = 'owner')),
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .import views


app_name = 'shop'

urlpatterns =[
    path('', views.homepage, name = 'homepage'),
    path('register', views.userRegister, name = 'userRegister'),
    path('login', views.loginpage, name ='login'),
    path('dologin', views.dologin, name = 'dologin'),
    path('logout',views.logout_user, name = "logout" ),
    path('allproducts', views.allproduct, name = 'allproduct'),
    path('allcategory', views.allcategory, name = 'allcategory'),
    path('product/<slug:slug>', views.specific, name = "specific"),
    path('product_details/<int:id>/<slug:slug>', views.product_details, name = 'product_details'),
    path('search', views.search, name= 'search'),
]

templates/adminpage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Admin page
{% endblock title %}

{% block content %}
<div class="container-fluid">
  
    {% if order %}
    <div class="text-center">
        <h5>Recent Order</h5>
        <small>
          Manage your recent order
        </small>
      </div>
      <br>
      {% for o in order  %}
      <div class="row">
        <main class="col-md-12">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Order ID: {{o.id}}</strong>
                <span>{{o.created}}</span> 
                <a href="{%url 'owner:sent_order' o.id%}">
                <button class='btn btn-warning'>
                    Add to Sent & Complete 
                </button>
                </a>
            </header>
            <div class="card-body">
                <div class="row"> 
                    <div class="col-md-8">
                        <h6 class="text-muted">Delivery to</h6>
                        <p>{{o.first_name}} {{o.last_name}} <br>  
                        Phone {{o.number}}<br>
                        Location: {{o.address}}, {{o.city}} <br> 
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h6 class="text-muted">Payment</h6>
                        <span class="text-success">
                           Hand Cash
                        </span>
                        <p>Subtotal: {{o.get_total_cost}} <br>
                         <span class="b">Total:  {{o.get_total_cost}} </span>
                        </p>
                    </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
            
            <div class="table-responsive">
            <table class="table table-hover">
                <tbody>
                  <p class='p-3'>Your Orders</p>
                  <hr>
                 {% for item in o.items.all %}
                 <tr>
                  <td width="65">
                      <img src="{%if item.product.image %}{{item.product.image.url}} {%else%} {%static 'images/1.jpg'%} {%endif%}" class="img-xs border" style="height: 50px;width: 50px;">
                  </td>
                  <td> 
                      <p class="title mb-0">{{item.product.name}} </p>
                      <var class="price text-muted">Rs. {{item.price}}</var>
                  </td>
                </tr>
                 {% endfor %}
                    
            </tbody></table>

            </div> <!-- table-responsive .end// -->
            
            </article> <!-- order-group.// --> 
        </main>
      </div>
      <br>
      {% endfor %}

        
    {% endif %}
      <hr>
      <div class="row p-2">
        <div class=" col-12 col-md-12 text-center">
            <h5>    Add     </h5>
            <small>
              You can add and manage your user, products and services
            </small>
          </div>
        <div class="col-6 col-md-3 p-2 addall">
            <a href="{%url 'owner:add_category'%}"> 
            <div class="text-center p-3" style="background-color: green; color: white;" >
             
              <h5 class="mt-2">
                Add Category
              </h5>
            </div>
            </a>
          </div>  
          <div class="col-6 col-md-3 p-2 addall">
            <a href="{%url 'owner:add_sub_cat'%}"> 
            <div class="text-center p-3" style="background-color: red; color: white;" >
                <h5 class="mt-2">
                    Add Sub Category
                  </h5>
            </div>
            </a>
          </div>  
          <div class="col-6 col-md-3 p-2 addall">
            <a href="{%url 'owner:add_product'%}"> 
            <div class="text-center p-3"  style="background-color: yellow; color:black;" >
             
              <h5 class="mt-2">
                Add Products
              </h5>
            </div>
            </a>
          </div>  
    
          <div class="col-6 col-md-3 p-2 addall">
            <a href="{%url 'owner:user_list'%}"> 
            <div class="text-center p-3" style="background-color: skyblue; color: white;" >
            
              <h5 class="mt-2">
                View Users
              </h5>
            </div>
            </a>
          </div>  
    
      </div>

</div>
{%endblock content%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Your Shop
        {% endblock title %}    
    </title>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="{%static 'css/bootstrap.css' %} " rel="stylesheet" type="text/css" media="all" />
<link href=" {%static 'css/style.css' %} " rel="stylesheet" type="text/css" media="all" />
<!-- CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!-- jQuery and JS bundle w/ Popper.js -->

<!-- font-awesome icons -->
<link href="{%static 'css/font-awesome.css' %} " rel="stylesheet" type="text/css" media="all" /> 
<!-- //font-awesome icons -->
<!-- js -->
<script src="{%static 'js/jquery-1.11.1.min.js' %} "></script>
<!-- //js -->
<link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="{%static 'js/move-top.js' %} "></script>
<script type="text/javascript" src="{%static 'js/easing.js' %} "></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
</head>
<body>
    <!-- header -->
	<div class="agileits_header">
		<div class='row'>
			<div class = 'col-12 col-md-8' >
				<div class="w3l_search">
					<form action="search" method="GET">
						{% csrf_token %}
						<input type="text" name="search" placeholder="Search a product..."  required>
						<input type="submit" value="">
					</form>
				</div>
			</div>
			<div class='col-6 col-md-2'>
				<div class="product_list_header" style="position:relative; display:inline-block;">  
					<input type="submit" name="submit" value="View your cart"  data-toggle="modal" data-target=".bd-example-modal-lg" class="button" />
				</div>
			</div>
			<div class = 'col-6 col-md-2'>
				<div class="w3l_header_right">
					<ul>
						<li class="dropdown profile_details_drop">
							
							{% if user.is_authenticated %}
							
							{% if user.user_type == 'owner' %}
							<a href="#" class="btn btn-secondary btn-sm dropdown-toggle m-1" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i> {{user}}</a>
							{%else%}
							<a href="#" class="btn btn-secondary btn-sm dropdown-toggle m-1" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i> {{user.first_name}}</a>
							{% endif %}
								
							
							{%else%}
							<a href="#" class="btn btn-secondary btn-sm dropdown-toggle m-1" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i> Login</a>
							{% endif %}
								
							
							<div class="mega-dropdown-menu">
								<div class="w3ls_vegetables">
									<ul class="dropdown-menu drp-mnu">
										
										{% if user.is_authenticated %}
										{% if user.user_type == 'owner' %}
											<li><a href="{%url 'owner:ownerDashboard'%}">Dashboard</a></li>
											<li><a href="{%url 'owner:adminOrder'%}">Order</a></li>  
											<li><a href="{%url 'shop:logout'%}">Logout</a></li>
										{%else%}
											<li><a href="{%url 'customer:dashboard'%}">Dashboard</a></li> 
											<li><a href="{%url 'shop:logout'%}">Logout</a></li>
										{% endif %}
										
										{%else%}
										<li><a href="{%url 'shop:login'%}">Login</a></li> 
										<li><a href="{%url 'shop:userRegister'%}">Sign Up</a></li>
										{% endif %}
											
										
									</ul>
								</div>                  
							</div>	
						</li>
					</ul>
				</div>
			</div>
		</div>
		
		<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-lg">
			  <div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Your Cart</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
				  </div>
				  <div class="modal-body">
					  
					  {% if cart %}
					  <div class="col-12 col-md-12 m-auto">
						<div class="row">
						<aside class="col-lg-12">
						<div class="card">
						<table class="table table-borderless table-shopping-cart">
						<thead class="text-muted">
						<tr class="small text-uppercase">
						  <th scope="col">Product</th>
						  <th scope="col" width="120">Price</th>
						  <th scope="col" class="text-right" width="200"> </th>
						</tr>
						</thead>
						<tbody>
							
						{% for cart in cart  %}
						<tr>
							<td>
								<figure class="itemside align-items-center">
									<div class="aside"><img src="
										{%if cart.product_name.image %}{{cart.product_name.image.url}}{%else%}{%static 'images/1.jpg'%}{%endif%}" class="img-sm" style="height: 70px; width: 70px;"></div>
									<figcaption class="info">
										<a href="#" class="title text-dark">{{cart.product_name.name}}</a>
										
									</figcaption>
								</figure>
							</td>
						
							<td> 
								<div class="price-wrap"> 
									<var class="price">Rs. {{cart.product_name.price}}</var> 
								</div> <!-- price-wrap .// -->
							</td>
							<td class="text-right"> 
							<a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a> 
							<a href="{%url 'customer:deleteCart' cart.id%}" class="btn btn-light"> Remove</a>
							</td>
						</tr>
						{% endfor %}
						</tbody>
						</table>
						
					
						</div> <!-- card.// -->
						
					</aside> <!-- col.// -->
							
						
						
						</div>
					</div>
					  {%else%}
					  <p class="text-center"> Your Cart is Empty</p>
					  {% endif %}
				
						  
				
				  </div>
				  <div class="modal-footer">
					<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
					
					{% if user.is_authenticated %}
					<a href="{%url 'customer:checkList'%}">
						<button type="button" class="btn btn-warning"> <i class="fa fa-shopping-cart"></i> Check Out</button>
					</a>
					{%else%}
						<button type="button" class="btn btn-warning disabled"> <i class="fa fa-shopping-cart"></i> Check Out</button>
					{% endif %}
						
					
					
				  </div>
			  </div>
			</div>
		</div>
	
	
		<div class="clearfix"> </div>
	</div>
<!-- script-for sticky-nav -->
	<script>
	$(document).ready(function() {
		 var navoffeset=$(".agileits_header").offset().top;
		 $(window).scroll(function(){
			var scrollpos=$(window).scrollTop(); 
			if(scrollpos >=navoffeset){
				$(".agileits_header").addClass("fixed");
			}else{
				$(".agileits_header").removeClass("fixed");
			}
		 });
		 
	});
	</script>
<!-- //script-for sticky-nav -->
	<div class="logo_products">
		<div class="container">
			<div class="w3ls_logo_products_left">
				<h1><a href="{%url 'shop:homepage'%}"><span>Our</span> Store</a></h1>
			</div>
			<div class="w3ls_logo_products_left1">
				<ul class="special_items">
					<li><a href="{%url 'shop:homepage'%}">Home</a><i>/</i></li>
					<li><a href="{%url 'shop:allcategory'%}">Categories</a><i>/</i></li>
					<li><a href="{%url 'shop:allproduct'%}">Products</a><i>/</i></li>
					<li><a href="#">About Us</a><i>/</i></li>
					<li><a href="#">Contact Us</a><i>/</i></li>
				</ul>
			</div>
			<div class="w3ls_logo_products_left1">
				<ul class="phone_email">
					<li><i class="fa fa-phone" aria-hidden="true"></i>01-4911122/9861252542</li>
					<li><i class="fa fa-envelope-o" aria-hidden="true"></i><a href="mailto:store@grocery.com">store@shop.com</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //header -->
{% block content %}
  
{% endblock content %}

<!-- footer -->
<div class="footer">
	<div class="container">
		
		<div class="clearfix"> </div>
		<div class="agile_footer_grids">
			<div class="col-md-3 w3_footer_grid agile_footer_grids_w3_footer">
				<div class="w3_footer_grid_bottom">
					<h4>100% Quality products</h4>
				</div>
			</div>
			<div class="col-md-3 w3_footer_grid agile_footer_grids_w3_footer">
				<div class="w3_footer_grid_bottom">
					<h5>connect with us</h5>
					<ul class="agileits_social_icons">
						<li><a href="#" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" class="twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" class="google"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
						<li><a href="#" class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
						<li><a href="#" class="dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<div class="wthree_footer_copy">
			<p>© 2020 Our Shop. All rights reserved | Design by <a href="http://dashpy.com/">DashPy Company</a></p>
		</div>
	</div>
</div>
<!-- //footer -->
<script src="{%static 'js/bootstrap.min.js' %} "></script>
<script>
$(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});
</script>
<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
				
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>
<!-- //here ends scrolling icon -->

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Check Out
{% endblock title %}
{% block loader %}
  
{% endblock loader %}
{% block content %}
  <div class="container">
    <div class="text-center">
      <h5>
        Review your cart and checkout
      </h5>
      <hr>
    </div>
    {% if messages%}
        {% for message in messages %}
        <div class="row">
            <div class="col-12 col-md-6 m-auto">
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{message}}
                   <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                     <span aria-hidden="true">&times;</span>
                   </button>
                 </div>
            </div>
        </div>
        {% endfor %}
      {% endif %}

      <div class="col-12 col-md-12 m-auto">
        <div class="row">
        <aside class="col-lg-9">
          <div class="card">
          <table class="table table-borderless table-shopping-cart">
          <thead class="text-muted">
          <tr class="small text-uppercase">
            <th scope="col">Product</th>
            <th scope="col" width="120">Quantity</th>
            <th scope="col" width="120">Price</th>
            <th scope="col" class="text-right" width="200"> </th>
          </tr>
          </thead>
          <tbody>
            {% for cart in cart  %}
            <tr>
              <td>
                <figure class="itemside align-items-center">
                  <div class="aside"><img src="{%if cart.product_name.image %}{{cart.product_name.image.url}} {%else%} {%static 'images/1.jpg'%} {%endif%}" class="img-sm" style="height: 70px; width: 70px;"></div>
                  <figcaption class="info">
                    <a href="#" class="title text-dark">{{cart.product_name.name}}</a>
                    
                  </figcaption>
                </figure>
              </td>
            
              <td> 
                <div class="price-wrap"> 
                  <var class="price">Rs. {{cart.product_name.price}}</var> 
                </div> <!-- price-wrap .// -->
              </td>
              <td class="text-right"> 
                <a href="{%url 'customer:deleteCart' cart.id%}" class="btn btn-light"> Remove</a>
              </td>
            </tr>
            {% endfor %}

        
            </tbody>
          </table>
          
          <div class="card-body border-top">
              <p class="icontext"><i class="icon text-success fa fa-truck"></i> Free Delivery within 1-2 weeks</p>
          </div> <!-- card-body.// -->
          
          </div> <!-- card.// -->
        
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
        
        <div class="card mb-3">
        <div class="card-body">
        </div> <!-- card-body.// -->
        </div> <!-- card.// -->
        
        <div class="card">
        <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">Rs. {{total_amount}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Discount:</dt>
                  <dd class="text-right text-danger">-Rs. {{discount}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>Rs. {{total_amount}}</strong></dd>
                </dl>
                <hr>
                <a href="{%url 'customer:delivery'%}" class="btn btn-primary btn-block"> Make Purchase </a>
                <a href="{%url 'shop:allproduct'%}" class="btn btn-light btn-block">Continue Shopping</a>
        </div> <!-- card-body.// -->
        </div> <!-- card.// -->
            </aside> <!-- col.// -->
        </div>
      </div>
    </div>
  </div>
  <br>
{% endblock content %}

templates/customerpage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Customer page
{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="row p-2">
        <div class=" col-12 col-md-12 text-center">
            <h5>    {{user.first_name}}    Dashboard</h5>
            <small>
              You can view and manage your order and other service
            </small>
          </div>
        <div class="col-6 col-md-4 p-2 addall">
            <a href="{%url 'customer:yourorder' user.customer.id%}"> 
            <div class="text-center p-3" style="background-color: green; color: white;" >
             
              <h5 class="mt-2">
                View my Orderlist
              </h5>
            </div>
            </a>
          </div>  
          <div class="col-6 col-md-4 p-2 addall">
            <a href="{%url 'shop:allcategory'%}"> 
            <div class="text-center p-3" style="background-color: red; color: white;" >
                <h5 class="mt-2">
                    See all Category
                  </h5>
            </div>
            </a>
          </div>  
          <div class="col-12 col-md-4 p-2 addall">
            <a href="{%url 'shop:allproduct'%}"> 
            <div class="text-center p-3"  style="background-color: yellow; color:black;" >
             
              <h5 class="mt-2">
                View all Products
              </h5>
            </div>
            </a>
          </div>  

      </div>
</div>
{%endblock content%}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Your Shop! Best Online Shopping
{% endblock title %}

{% block content %}

<!-- banner -->
	<div class="banner">
		<div class="w3l_banner_nav_left">
			<nav class="navbar nav_bottom">
			 <!-- Brand and toggle get grouped for better mobile display -->
			  <div class="navbar-header nav_2">
				  <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				  </button>
			   </div> 
			   <!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
					<h6 class="text-center">Categories</h6>
					<ul class="nav navbar-nav nav_1">
						<li><a href="{%url 'shop:allcategory'%}">All</a></li>	
						{% for c in cat  %}
						<li><a href="{{c.get_absolute_url}}">{{c}}</a></li>	
						{% endfor %}
					</ul>
				 </div><!-- /.navbar-collapse -->
			</nav>
		</div>
		<div class="w3l_banner_nav_right">
			<div class="card card-body">
				<h6 class="btn btn-warning">Our Latest Products</h6>
				<br>
				<div class="row">

					{% for p in fixed_product  %}
					<div class="col-md-3 col-6">
						<figure class="card card-product-grid">
							<div class="img-wrap"> 
								<a href="{%url 'shop:product_details' p.id p.slug%}">
									<img src="{%if p.image %}{{p.image.url}} {%else%} {%static 'images/1.jpg'%} {%endif%}" style="height: 200px; width: 100%;"> </div>
								</a>
								
							<figcaption class="info-wrap border-top">
								<a href="{%url 'shop:product_details' p.id p.slug%}" class="title p-2 text-capitalize" style="color: black;">{{p.name}}</a>
								<div class="price mt-2 pl-2"> <b>Rs.{{p.price}}</b> </div> <!-- price-wrap.// -->
								<div class="snipcart-details top_brand_home_details mb-4">
									<a href="{%url 'customer:addtocart' p.id%}">
										<input type="submit" name="submit" value="Add to cart" class="button" />
									</a>
								</div>
							</figcaption>
							
						</figure> <!-- card // -->
					</div>
					{% endfor %}
					
				</div> <!-- row.// -->
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
<!-- banner -->

<!-- top-brands -->
	<div class="top-brands">
		<div class="container">
			<h3>Top Products</h3>
			<div class="agile_top_brands_grids">
				<div class="row">
					{% for p in product  %}
					<div class="col-md-3 col-6">
						<figure class="card card-product-grid">
							<div class="img-wrap"> 
								<a href="{%url 'shop:product_details' p.id p.slug%}">
									<img src="{%if p.image %}{{p.image.url}} {%else%} {%static 'images/1.jpg'%} {%endif%}" style="height: 200px; width: 100%;"> </div>
								</a>
							<figcaption class="info-wrap border-top">
								<a href="{%url 'shop:product_details' p.id p.slug%}" class="title p-2 text-capitalize" style="color: black;">{{p.name}}</a>
								<div class="price mt-2 pl-2"> <b>Rs.{{p.price}}</b> </div> <!-- price-wrap.// -->
								<div class="snipcart-details top_brand_home_details mb-4">
									<a href="{%url 'customer:addtocart' p.id%}">
										<input type="submit" name="submit" value="Add to cart" class="button" />
									</a>
								</div>
							</figcaption>
							
						</figure> <!-- card // -->
					</div>
					{% endfor %}
				</div>
				
				<div class="clearfix"> </div>
			</div>
			<hr>
			<div class="row">
				<div class="col-md-5 col-8 m-auto">
					<div class="text-center">
						<a class="btn btn-warning btn-block" href="{%url 'shop:allproduct'%}">
							See all Products
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="newsletter">
		<div class="container">
			<div class="w3agile_newsletter_left">
				<h3>sign up for our newsletter</h3>
			</div>
			<div class="w3agile_newsletter_right">
				<form action="#" method="post">
					<input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
					<input type="submit" value="subscribe now">
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //newsletter -->

{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Login to shop
{% endblock title %}

{% block content %}
<div class="container-fluid">
    {% if messages%}
        {% for message in messages %}
        <div class="row">
            <div class="col-6 m-auto" style= "background-color:crimson; padding: 2px; color: white;">
                <p class="text-center">
                    {{message}}
                </p>
            </div>
        </div>
       
        {% endfor %}
      {% endif %}
        <div class="w3_login" style="padding: 0px;">
			<h3>Sign In</h3>
			<div class="w3_login_module">
				<div class="module form-module">
				  <div class="toggle"><i class="fa fa-user-circle"></i>
					
				  </div>
				  <div class="form">
					<h2>Login to your account</h2>
					<form action="dologin" method="post">
					  <input type="text" name="email" placeholder="Username" required=" ">
                      <input type="password" name="password" placeholder="Password" required=" ">
                      {% csrf_token %}
                      <input type="submit" value="Login">
                      <hr>
                      <a href="{%url 'shop:userRegister'%}">
                          <div class="btn btn-warning btn-block">
                            Sign Up
                          </div>
                      </a>
                      
					</form>
				  </div>
				 
				  <div class="cta"><a href="#">Forgot your password?</a></div>
				</div>
			</div>

		</div>
 
</div>
{%endblock content%}